apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  labels:
    operator.kyma-project.io/controller-name: kyma
    operator.kyma-project.io/managed-by: Kyma
    operator.kyma-project:.io/kyma-name: kyma-sample
  name: kyma-sample
  namespace: default
spec:
  profile: "production"
  channel: stable
  modules:
    - name: example-module-name
      controller: manifest
      channel: stable
      overrides:
        - name: nginx-ingress
          selector:
            matchLabels:
              extension.kyma-project.io/config-override: "a"
  sync:
    enabled: true
    namespace: kyma-system
    strategy: local-secret
