apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: cert-kcp
  namespace: istio-system
spec:
  commonName: "*.j2fmn4e1n7.jellyfish.shoot.canary.k8s-hana.ondemand.com"
  dnsNames:
    - "wat.j2fmn4e1n7.jellyfish.shoot.canary.k8s-hana.ondemand.com"
  secretRef:
    name: kcp-tls
    namespace: istio-system
  issuerRef:
    name: issuer-ca
    namespace: istio-system
---

apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: cert-skr
  namespace: istio-system
spec:
  commonName: "*.j2fmn4e1n7.jellyfish.shoot.canary.k8s-hana.ondemand.com"
  dnsNames:
    - "wat.j2fmn4e1n7.jellyfish.shoot.canary.k8s-hana.ondemand.com"
    - "localhost"
    - "watcher-webhook.default.svc.cluster.local"
    - "watcher-webhook.default.svc"
  secretRef:
    name: skr-tls
    namespace: istio-system
  issuerRef:
    name: issuer-ca
    namespace: istio-system
---

#If one of the accepted DNS names is a direct subname of the shoot’s ingress domain, this is already handled by the standard wildcard entry for the ingress domain.
#Therefore, this name should be excluded from the dnsnames list in the annotation.
#If only this DNS name is configured in the ingress, no explicit DNS entry is required, and the DNS annotations should be omitted at all.
#apiVersion: dns.gardener.cloud/v1alpha1
#kind: DNSEntry
#metadata:
#  annotations:
#    dns.gardener.cloud/class: garden
#  name: dns-entry
#  namespace: watcher
#spec:
#  dnsName: wat.j2fmn4e1n7.jellyfish.shoot.canary.k8s-hana.ondemand.com
#  targets:
#    - j2fmn4e1n7.jellyfish.shoot.canary.k8s-hana.ondemand.com

---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Issuer
metadata:
  name: issuer-ca
  namespace: istio-system
spec:
  ca:
    privateKeySecretRef:
      name: issuer-ca-secret
      namespace: istio-system